platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

target 'Profile Sample' do
  pod 'Lock', '~> 1.21'
  pod 'Lock-Facebook', '~> 2.2'
  pod 'SimpleKeychain', '~> 0.6'
  pod 'JWTDecode', '~> 1.0'
  pod 'Alamofire', '~> 2.0'
  pod 'Auth0', '~> 0.2'
  pod 'MBProgressHUD', '~> 0.9.1'
end