platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

target 'Profile Sample' do
  pod 'Lock', '~> 1.14'
  pod 'Lock-Facebook', '~> 2.0'
  pod 'SimpleKeychain', '~> 0.4'
  pod 'JWTDecode', '~> 0.3'
  pod 'Alamofire', '~> 1.2'
  pod 'Auth0', '~> 0.1'
  pod 'MBProgressHUD', '~> 0.9.1'
end

target 'Auth0Storage' do
  pod 'Lock/Core', '~> 1.14'
  pod 'SimpleKeychain', '~> 0.4'
  pod 'JWTDecode', '~> 0.3'
end