platform :ios, '8.0'

target 'ReactNativeSample' do
  pod 'LockReactNative', :path => 'node_modules/react-native-lock-ios'

  pod 'React', :path => 'node_modules/react-native', :subspecs => [
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    # Add any other subspecs you want to use in your project
  ]
end
