# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'Evilation' do
  pod 'Lock', '~> 1.16', :subspecs => ['WebView', 'Core']
  pod 'Lock-Facebook', '~> 2.0'
  pod 'MBProgressHUD', '~> 0.9.1'
end
