# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'Evilation' do
  pod 'Lock', '~> 1.16', :subspecs => ['WebView', 'Core']
  pod 'Lock-Facebook', '~> 2.0'
  pod 'MBProgressHUD', '~> 0.9.1'
end

post_install do |installer|
    installer.pods_project.build_configurations.each { |bc|
        bc.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    }
end